### PR TITLE
Update puppet-xp.ts

### PR DESCRIPTION
**Pull request by smallfourRich**
修复msgsource时报错，修复无讲话人报错

----

| :rocket: | This description was created by [Ellipsis](https://www.ellipsis.dev) for commit 129fd0edd383f9f01855a8a1b7e49a9d6e4fc2fe  | 
|--------|--------|

### Summary:
Fixes errors in `onHookRecvMsg` by adding checks for undefined `msgsource` and ensuring `talkerId` is present before emitting events in `src/puppet-xp.ts`.

**Key points**:
- Fix error in `onHookRecvMsg` when `msgsource` is undefined or null by adding checks.
- Ensure `talkerId` is present before emitting a message event in `onHookRecvMsg`.
- Modify `if` condition in `onHookRecvMsg` to handle cases with no speaker.

----
Generated with :heart: by [ellipsis.dev](https://www.ellipsis.dev)

### CODE REVIEW

**Review by atorber — COMMENTED** [review]
private onHookRecvMsg (args: any) {
    //log.info('onHookRecvMsg', JSON.stringify(args))
    let type = PUPPET.types.Message.Unknown
    let roomId = ''
    let toId = ''
	@@ -251,7 +251,7 @@ class PuppetXp extends PUPPET.Puppet {
          xml2js.parseString(String(args[4]), { explicitArray: false, ignoreAttrs: true }, function (err: any, json: any) {
            log.verbose('PuppetXp', 'xml2json err:%s', err)
            //  log.verbose('PuppetXp', 'json content:%s', JSON.stringify(json))
            if (undefined !== json && null !== json && json.msgsource && json.msgsource.atuserlist === 'atuserlist') {
              type = PUPPET.types.Message.GroupNote
            } else {
              type = PUPPET.types.Message.Text
	@@ -497,7 +497,7 @@ class PuppetXp extends PUPPET.Puppet {
          }
        } else {
          this.messageStore[payload.id] = payload
          if (payload.talkerId && this.isReady) {
            this.emit('message', { messageId: payload.id })
          }
        }
	@@ -648,10 +648,10 @@ class PuppetXp extends PUPPET.Puppet {
  }

**Comment by atorber** [comment]
> private onHookRecvMsg (args: any) { //log.info('onHookRecvMsg', JSON.stringify(args)) let type = PUPPET.types.Message.Unknown let roomId = '' let toId = '' @@ -251,7 +251,7 @@ class PuppetXp extends PUPPET.Puppet { xml2js.parseString(String(args[4]), { explicitArray: false, ignoreAttrs: true }, function (err: any, json: any) { log.verbose('PuppetXp', 'xml2json err:%s', err) // log.verbose('PuppetXp', 'json content:%s', JSON.stringify(json)) if (undefined !== json && null !== json && json.msgsource && json.msgsource.atuserlist === 'atuserlist') { type = PUPPET.types.Message.GroupNote } else { type = PUPPET.types.Message.Text @@ -497,7 +497,7 @@ class PuppetXp extends PUPPET.Puppet { } } else { this.messageStore[payload.id] = payload if (payload.talkerId && this.isReady) { this.emit('message', { messageId: payload.id }) } } @@ -648,10 +648,10 @@ class PuppetXp extends PUPPET.Puppet { }

Modifying this method may not seem like the best solution. This change will ignore normal messages that do not contain talkerid.

**Comment by smallfourRich** [comment]
> > private onHookRecvMsg (args: any) { //log.info('onHookRecvMsg', JSON.stringify(args)) let type = PUPPET.types.Message.Unknown let roomId = '' let toId = '' @@ -251,7 +251,7 @@ class PuppetXp extends PUPPET.Puppet { xml2js.parseString(String(args[4]), { explicitArray: false, ignoreAttrs: true }, function (err: any, json: any) { log.verbose('PuppetXp', 'xml2json err:%s', err) // log.verbose('PuppetXp', 'json content:%s', JSON.stringify(json)) if (undefined !== json && null !== json && json.msgsource && json.msgsource.atuserlist === 'atuserlist') { type = PUPPET.types.Message.GroupNote } else { type = PUPPET.types.Message.Text @@ -497,7 +497,7 @@ class PuppetXp extends PUPPET.Puppet { } } else { this.messageStore[payload.id] = payload if (payload.talkerId && this.isReady) { this.emit('message', { messageId: payload.id }) } } @@ -648,10 +648,10 @@ class PuppetXp extends PUPPET.Puppet { }
> 
> Modifying this method may not seem like the best solution. This change will ignore normal messages that do not contain talkerid.

但是目前，这个talker的消息，会

**Comment by atorber** [comment]
The recommended approach is to first determine the message type obtained by onHookRecvMsg, and handle it based on the type. The msg that does not contain talkerid is not of the message type.

**Pull request closed without merging**
