### PR TITLE
fixed #86 wxstring struct size

### LINKED ISSUE #86: when call contact.say(msg) ,  the wechat client shutdown
#### by follow steps:
1. delete folder \Documents\WeChat Files
2. login wechat( ***do not select sync data*** ) _necessary_
3. contact.say to anybody
```
async function onLogin (user: Contact) {
  log.info('StarterBot', '%s login', user)
  const contactList = await bot.Contact.findAll()
  contactList.forEach(c => {
    if (c.name() === 'A') {
        c.say('hi')
      }
  })

}
```
```
17:48:23 ERR Config Wechaty unhandledRejection: Error: Script is destroyed
    at onScriptDestroyed (D:\Programing\Projects\puppet-xp\node_modules\frida\dist\script.js:118:26) [object Promise]
17:48:23 ERR Config ###########################
17:48:23 ERR Config process.on(unhandledRejection) promise.catch(Script is destroyed)
Config Error: Script is destroyed
    at onScriptDestroyed (D:\Programing\Projects\puppet-xp\node_modules\frida\dist\script.js:118:26)
```
L1VzZXJzL2xpYW5namlhbmNoYW8vTGlicmFyeS9BcHBsaWNhdGlvbiBTdXBwb3J0L0RpbmdUYWxrTWFjLzM1NDQxOTU0X3YyL0ltYWdlRmlsZXMvMTY0NTAwNTY4NTQ0M19GMEE3OUM4NC01OTBDLTRBMTEtQUZEOC05MzI0QzM5N0M1NjMucG5n

### PR DESCRIPTION
**Pull request by lgojc**
L1VzZXJzL2xpYW5namlhbmNoYW8vTGlicmFyeS9BcHBsaWNhdGlvbiBTdXBwb3J0L0RpbmdUYWxrTWFjLzM1NDQxOTU0X3YyL0ltYWdlRmlsZXMvMTY0NjEwNzMzMjc4OF8zMEJGQjA0RS1EMTdCLTRBMjUtOUZDRC0zMkQ4RTA1NTQ4RTAucG5n

### CODE REVIEW

**Comment by starzou** [comment]
@atorber @huan Any ideas?

**Review by starzou — APPROVED** [review]

**Review by huan — APPROVED** [review]
LGTM

**Comment by huan** [comment]
## Wechaty Contributors Nomination

Link to https://github.com/wechaty/PMC/issues/16

**Comment by huan** [comment]
Thank you very much for your contribution!

## You are welcome to join [Wechaty Contributor Program](https://wechaty.js.org/docs/contributor-program/)

### 1. Join Wechaty Organization

> [](https://github.com/wechaty)You've invited lgojc to Wechaty! They'll be receiving an email shortly. They can also visit https://github.com/wechaty to accept the invitation.

I have invited you to join our Wechaty GitHub Organization, please accept it by following the above message. (See also: [wechaty/PMC#16](https://github.com/wechaty/PMC/issues/16))

### 2. Update Your Wechaty Contributor Profile

1. Please open [Contributor Hall of Fame](https://docs.google.com/spreadsheets/d/1XcDoIczyIclqXP1p90Sz7S0n4Q22xjFzJmjPFlU2g1E/edit#gid=0) and add yourself to the end of the list, so that other contributors will know you better!
1. Please add yourself to our Website [Contributors](https://wechaty.js.org/contributors/) by [creating a PR](https://github.com/wechaty/wechaty.js.org/tree/master/jekyll/_contributors) and refer to this PR link as well.

### 3. Join The Contributor Only WeChat Room

We also have a WeChat room for contributors only which can discuss Wechaty at a deeper level, you are welcome to join and if you are interested.

Please add @lijiarui wechat: _ruirui_0914_ and send her this pr link. She will invite you into Wechaty Contributor Room

Cheers!

**Pull request merged**
