### PR TITLE
Update examples/ding-dong-bot.ts

### PR DESCRIPTION
**Pull request by pea-cake**
Variable name error

### CODE REVIEW

**Comment by huan** [comment]
## Wechaty Contributors Nomination

Link to https://github.com/wechaty/PMC/issues/16

**Comment by pea-cake** [comment]
> Please make sure the following requirements have been met for your PR before we can continue reviewing it:
> 
> 1. You have signed the CLA by clicking the `[CLA | not signed yet]` button from the comments.
> 2. The PR has passed all the CI tests and turns _green_. (you can execute all tests locally by running `npm test`)

ok, thanks

**Comment by huan** [comment]
Thank you very much for your contribution!

## You are welcome to join [Wechaty Contributor Program](https://wechaty.js.org/docs/contributor-program/)

### 1. Join Wechaty Organization

> [](https://github.com/wechaty)You've invited peacake to Wechaty! They'll be receiving an email shortly. They can also visit https://github.com/wechaty to accept the invitation.

I have invited you to join our Wechaty GitHub Organization, please accept it by following the above message. (See also: [wechaty/PMC#16](https://github.com/wechaty/PMC/issues/16))

### 2. Update Your Wechaty Contributor Profile

1. Please open [Contributor Hall of Fame](https://docs.google.com/spreadsheets/d/1XcDoIczyIclqXP1p90Sz7S0n4Q22xjFzJmjPFlU2g1E/edit#gid=0) and add yourself to the end of the list, so that other contributors will know you better!
1. Please add yourself to our Website [Contributors](https://wechaty.js.org/contributors/) by [creating a PR](https://github.com/wechaty/wechaty.js.org/tree/master/jekyll/_contributors) and refer to this PR link as well.

### 3. Join The Contributor Only WeChat Room

We also have a WeChat room for contributors only which can discuss Wechaty at a deeper level, you are welcome to join and if you are interested.

Please add @lijiarui wechat: _ruirui_0914_ and send her this pr link. She will invite you into Wechaty Contributor Room

Cheers!

**Comment by pea-cake** [comment]
Cheers!

**Comment by lijiarui** [comment]
> Please add yourself to our Website [Contributors](https://wechaty.js.org/contributors/) by [creating a PR](https://github.com/wechaty/wechaty.js.org/tree/master/jekyll/_contributors) and refer to this PR link as well.

@pea-cake This link is outdated now, you can add your profile to our website by creating a PR here: https://github.com/wechaty/jekyll/tree/main/jekyll/_contributors

**Pull request merged**
